version: '3.8'

services:
  app:
    image: crystalbackend.azurecr.io/nestjs-clean-code-architecture:latest # Replace with your actual image name
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
#     environment:
#       NODE_ENV: production
#       DATABASE_HOST: db
#       DATABASE_PORT: 5432
#       DATABASE_USER: postgres
#       DATABASE_PASSWORD: postgres
#       DATABASE_NAME: mydatabase
#     depends_on:
#       - db

#   db:
#     image: postgres:13
#     ports:
#       - '5432:5432'
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: postgres
#       POSTGRES_DB: mydatabase
#     volumes:
#       - postgres_data:/var/lib/postgresql/data

# volumes:
#   postgres_data:
