# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - crystal-backend
on:
  push:
    branches:
    - main
    - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        registry: ${{secrets.REGISTRY}}
    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/amd64 -t crystalbackend.azurecr.io/nestjs-clean-code-architecture:v1 --push .
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0B08870754B64A1E9FADDE3C4ACCF875 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B6EF15F28059499783FB1513040375F4 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_199D40728CE44D2F90DA2B85612199CB }}
    - name: Deploy to Azure Web App
      run: |
        az webapp config container set --resource-group ingestion --name crystal-backend --docker-custom-image-name crystalbackend.azurecr.io/nestjs-clean-code-architecture:v1
        az webapp restart --resource-group ingestion --name crystal-backend


